services:
  db:
    image: postgres:17-alpine
    restart: always
    container_name: college_connect_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: college_connect
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Development ---
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    container_name: college_connect_app_dev
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    # Use pnpm to run the dev server
    command: sh -c "pnpm install && pnpm prisma generate && pnpm dev"

  # --- Production Service ---
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: college_connect_app_prod
    restart: always
    depends_on:
      - db
    ports:
      - "8080:3000"
    env_file:
      - .env.production

volumes:
  postgres_data:
