export const VALID_ORDER_TRANSITIONS = {
  NEW: ["BATCHED", "CANCELLED"],
  BATCHED: ["OUT_FOR_DELIVERY", "CANCELLED"],
  OUT_FOR_DELIVERY: ["COMPLETED", "CANCELLED"],
  COMPLETED: [],
  CANCELLED: [],
} as const;
