export const VALID_ORDER_TRANSITIONS = {
  NEW: ["BATCHED", "CANCELLED"],
  BATCHED: ["OUT_FOR_DELIVERY", "CANCELLED"],
  OUT_FOR_DELIVERY: ["COMPLETED", "DELIVERY_FAILED", "CANCELLED"],
  COMPLETED: [],
  CANCELLED: [],
  DELIVERY_FAILED: ["CANCELLED"],
  RESCHEDULED: ["OUT_FOR_DELIVERY", "CANCELLED"],
} as const;
